sort:main.cpp InsertSort.cpp ShellSort.cpp SimpleSelectionSort.cpp HeapSort.cpp BubbleSort.cpp
	g++ -o sort main.cpp InsertSort.cpp ShellSort.cpp SimpleSelectionSort.cpp HeapSort.cpp BubbleSort.cpp QuickSort.cpp
 
